src/Entity/Recettage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;


/**
 * @ORM\Entity(repositoryClass="App\Repository\RecettageRepository")
 */
class Recettage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $navigator;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $ask;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $ask_fonctionality;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getNavigator(): ?string
    {
        return $this->navigator;
    }

    public function setNavigator(string $navigator): self
    {
        $this->navigator = $navigator;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAsk(): ?string
    {
        return $this->ask;
    }

    public function setAsk(?string $ask): self
    {
        $this->ask = $ask;

        return $this;
    }

    public function getBug(): ?string
    {
        return $this->bug;
    }

    public function setBug(?string $bug): self
    {
        $this->bug = $bug;

        return $this;
    }

    public function getAskFonctionality(): ?string
    {
        return $this->ask_fonctionality;
    }

    public function setAskFonctionality(?string $ask_fonctionality): self
    {
        $this->ask_fonctionality = $ask_fonctionality;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/RecettageType.php
<?php

namespace App\Form;

use App\Entity\Recettage;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecettageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('navigator')
            ->add('status')
            ->add('ask')
            ->add('bug')
            ->add('ask_fonctionality')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recettage::class,
            'translation_domain' => 'forms_Recettage'
        ]);
    }
}

src/Controller/RecettageController.php
<?php

namespace App\Controller;

use App\Entity\Recettage;
use App\Form\RecettageType;
use App\Repository\RecettageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class RecettageController extends AbstractController
{

    private $recettageRepository;

    public function __construct(RecettageRepository $recettageRepository, EntityManagerInterface $em)
    {
        $this->recettageRepository = $recettageRepository;
        $this->em = $em;
    }

    /**
     * @Route("/newRecettage", name="new_recettage")
     */
    public function new(Request $request)
    {
        $recettage = new Recettage;
        $recettageForm = $this->createForm(RecettageType::class, $recettage);
        $recettageForm->handleRequest($request);

        if ($recettageForm->isSubmitted() && $recettageForm->isValid()) {
            $this->em->persist($recettage);
            $this->em->flush();
            

            return $this->redirectToRoute('historique');
        }

        return $this->render('recettage/newRecettage.html.twig', [
            'recettage' => $recettage,
            'recettageForm' => $recettageForm->createView(),
            'current_menu' => 'creationRecettage'
        ]);
    }
}

templates/recettage/_recettage.html.twig
<div class="col-3">
    <div class="card">
        <div class="card-body">
            <div class="card-title">
                <h5>
                    <a href="{{ path('recettage_show', {id: recettage.id, slug: recettage.slug}) }}">{{ recettage.title }}</a>
                </h5>
                        <p class="card-text">{{ recettage.navigator }}</p>
                <div class="text-primary">
                    <a href="{{ path('pdfRecettage', {id: recettage.id, slug: recettage.slug}) }}" class="btn btn-primary">Telecharger le recettage</a>
                </div>
            </div>
        </div>
    </div>
</div>

templates/recettage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecettageController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Users/HarrisonPro/Desktop/Awebi/src/Controller/RecettageController.php'|file_link(0) }}">src/Controller/RecettageController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Users/HarrisonPro/Desktop/Awebi/templates/recettage/index.html.twig'|file_link(0) }}">templates/recettage/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/recettage/newRecettage.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'un recettage{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="text-center">Créer le recettage</h1>
       {{ include ('admin/rapport/_formRecettage.html.twig', {form: recettageForm, button: 'Enregistrer'}) }}
    </div>
{% endblock %}

templates/recettage/pdfRecettage.html.twig
{% block body %}
    <div class="jumbotron">
        <div class="container">
            <h1>Recettage: {{ recettage.title }} - {{ recettage.createdAt | date("m/d/Y") }} à {{ recettage.createdAt | date("H:i") }}</h1>
        </div>
    </div>

    <div class="container mt-4">
        <div class="col-md-6">
            <h2>Navigateur : {{ recettage.navigator }}</h2>
            <h2>Status de la fonctionalité : {{ recettage.status }}</h2>
            <h2>Poser une question : {{ recettage.ask | nl2br }}</h2>
            <h2>Signaler un buf : {{ recettage.bug }}</h2>
            <h2>Demander une fonctionalité : {{ recettage.askfonctionality }}</h2>
        </div>
    </div>
{% endblock %}

templates/recettage/showRecettage.html.twig
{% extends "base.html.twig" %}

{% block title recettage.title %}

{% block body %}
    {# <rapport>
            <h2>Titre du rapport</h2>
            <div class="metadata">Rapport du 10/05/2020 à 15:00</div>
            <a href="" class="btn btn-primary">Telecharger le rapport</a>
    </rapport> #}

    <div class="jumbotron">
        <div class="container">
            <h1>Recettage: {{ recettage.title }} - {{ recettage.createdAt | date("m/d/Y") }} à {{ recettage.createdAt | date("H:i") }}</h1>
        </div>
    </div>

    <div class="container mt-4">
        <div class="col-md-6">
            <h2>Navigateur : {{ recettage.navigator }}</h2>
            <h2>Status de la fonctionalité : {{ recettage.status }}</h2>
            <h2>Poser une question : {{ recettage.ask | nl2br }}</h2>
            <h2>Signaler un bug : {{ recettage.bug }}</h2>
            <h2>Demander une fonctionalité : {{ recettage.askfonctionality }}</h2>

            <a href="{{ path('pdfRecettage', {id: recettage.id, slug: recettage.slug}) }}" class="btn btn-primary">Telecharger le recettage</a>
        </div>
    </div>
{% endblock %}